server:
  port: 9191

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/demo
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  application:
    name: PROFILE-SERVICE
  rabbitmq:
    host: rabbitmq-0.rabbitmq.default.svc.cluster.local
    port: 5672
  cloud:
    stream:
      bindings:
        postCreated-in-0:
          destination: post-events

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka