apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service-app
  labels:
    app: post-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : post-service-app
  template:
    metadata:
      labels:
        app: post-service-app
    spec:
      containers:
      - name: post-service-app
        image: snowkid/post-service:latest
        args: ["--spring.profiles.active=prod"]
        imagePullPolicy: Always
        ports:
          - containerPort: 9192
        resources:
          requests:
            memory: "200Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "1000m"

---

kind: Service
apiVersion: v1
metadata:
  name:  post-service-svc
spec:
  selector:
    app:  post-service-app
  ports:
  - port:  80
    targetPort:  9192