server:
  port: 9192

spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: dev
  application:
    name: POST-SERVICE
  rabbitmq:
    host: rabbitmq-0.rabbitmq.default.svc.cluster.local
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        postCreated-out-0:
          destination: post-events

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
