server:
  port: 9192

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dev
  application:
    name: POST-SERVICE
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        postCreated-out-0:
          destination: post-events

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost