name: Gateway CI/CD

defaults:
  run:
    working-directory: backend/cloud-gateway

on:
  push:
    branches: master
  pull_request:
    branches: master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build
      run: mvn clean package
  docker:
    environment: docker
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Gateway
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./
          tags: snowkid/cloud-gateway:latest
