name: Profile Service CI/CD

defaults:
  run:
    working-directory: backend/profile-service

on:
  push:
    branches: master
  pull_request:
    branches: master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build and release
      run: mvn clean package dockerfile:push -Ddockerfile:username=$DOCKER_USERNAME -Ddockerfile:password=$DOCKER_PASSWORD
